<?php

namespace oihana\zitadel\enums;

/**
 * Authentication method types for Zitadel API applications.
 *
 * Mirrors the `AuthMethodType` enum from the Zitadel ApplicationService
 * V2 (`apiConfiguration.authMethodType`) and the V1 `AddAPIApp` body.
 *
 * Two flows are supported :
 *
 * - {@see self::BASIC} — the application authenticates at the
 *   introspection endpoint (Zitadel-side validation of tokens it did
 *   NOT mint) using `Authorization: Basic base64(clientId:clientSecret)`.
 *   The clientSecret is generated by Zitadel and returned **once** on
 *   creation. The application itself cannot mint tokens via the
 *   `/oauth/v2/token` endpoint — `client_credentials` against an API
 *   app with BASIC auth returns `400 invalid_client` ("client not
 *   found"). To obtain access tokens, a separate Service User must be
 *   wired (or use the {@see self::PRIVATE_KEY_JWT} flow below).
 *
 * - {@see self::PRIVATE_KEY_JWT} — the application authenticates with
 *   asymmetric cryptography. Zitadel does NOT generate a clientSecret
 *   on creation ; instead, a JSON keyfile carrying an RSA private key
 *   + keyId is generated separately through the `CreateApplicationKey`
 *   endpoint, returned once and never stored server-side. The client
 *   then signs a short-lived JWT bearer assertion with that private
 *   key and exchanges it at `/oauth/v2/token` with
 *   `grant_type=client_credentials` + `client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer`
 *   + the signed `client_assertion`. Recommended for M2M flows.
 *
 * @package oihana\zitadel\enums
 * @author  Marc Alcaraz
 */
class ZitadelAppAuthMethod
{
    /**
     * Basic Auth — clientId + clientSecret in the `Authorization`
     * header. The clientSecret is generated by Zitadel on creation and
     * returned only in the create response. Cannot mint tokens
     * directly through `client_credentials` on Zitadel API apps.
     */
    public const string BASIC = 'API_AUTH_METHOD_TYPE_BASIC' ;

    /**
     * Private Key JWT — the client signs a JWT bearer assertion with
     * the RSA private key carried by the JSON keyfile generated by
     * Zitadel's `CreateApplicationKey` endpoint. The signed assertion
     * is exchanged at the token endpoint for an access token.
     */
    public const string PRIVATE_KEY_JWT = 'API_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT' ;
}
